version: "2"
services:
  laas-controller:
    image: timelimited/laas-controller:0.0.1-dev-enhancement-84
    restart: always
    depends_on:
      l1s-controller:
        condition: service_started
    command:
      - "-netbox-host"
      - "172.21.179.140:8000" #update with netboxhostname:port
      - "-netbox-user-token"
      - "fa44230eef4a757fdf8591f82d7a41cfadd95e96" #update with netbox user token
      - "-framework-name"
      - "cafy"
      - "-trs-l1s-controller"
      - "l1s-controller:9000"

  l1s-controller:
    image: production/l1s-controller:0.0.1-9
    restart: always
    command:
      - "-l1switch-host"
      - "172.27.136.23"
      - "-l1switch-model"
      - "calient"
      - "-l1switch-user"
      - "admin"
      - "-l1switch-pass"
      - "pxc***"