version: "2"
services:
  laas-controller:
    image: ghcr.io/open-traffic-generator/lab-reservation-service:0.0.6
    restart: always
    depends_on:
      l1s-controller:
        condition: service_started
    command:
      - "-netbox-host"
      - "obox0.lbj.is.keysight.com:3000"
      - "-netbox-user-token"
      - "6b64424662329f2204003e0d8bf213035b2034dd"
      - "-framework-name"
      - "ondatra"
      - "-l1switch-location"
      - "l1s-controller:9000"
    ports:
      - "8080:8080"

  l1s-controller:
    image: ghcr.io/open-traffic-generator/l1s-service:0.0.1
    restart: always
    command:
      - "-l1switch-host"
      - "10.36.237.181"
      - "-l1switch-port"
      - "8000"
      - "-l1switch-model"
      - "visionpb"
      - "-l1switch-user"
      - "admin"
      - "-l1switch-pass"
      - "admin"
    ports:
      - "9000:9000"
 